<?xml version="1.0"?>
<package format="3">
  <name>trip_description</name>
  <version>0.0.1</version>
  <description>
    URDF and meshes for TRIP, usable in RViz and Gazebo.
  </description>

  <maintainer email="davidedorigoni@gmail.com">DavDori</maintainer>
  <license>Apache-2.0</license>

  <!-- Build system -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Runtime dependencies -->
  <exec_depend>xacro</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>gazebo_ros</exec_depend>

  <!-- To make sure other packages can find your description -->
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>